# Generated by Django 4.0.3 on 2022-05-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepPortalUserToken',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rp_token', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(help_text='RepPortal user specific token', max_length=300, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='featurebuild',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='testset',
            options={'ordering': ['name']},
        ),
    ]
