# Generated by Django 4.0.3 on 2022-08-04 14:51

from django.db import migrations, models
import django.db.models.deletion


def remove_test_instances(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    TestInstance = apps.get_model("tra", "TestInstance")
    db_alias = schema_editor.connection.alias
    TestInstance.objects.using(db_alias).all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0002_testrun_airphone_testsetfilter_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_test_instances),
    
        # migrations.RemoveField(
        #     model_name='testset',
        #     name='branch',
        # ),
        # migrations.AlterField(
        #     model_name='testinstance',
        #     name='test_set',
        #     field=models.ForeignKey(blank=False, help_text='Test set', on_delete=django.db.models.deletion.CASCADE, to='tra.testsetfilter')
        # ),

        # migrations.DeleteModel(
        #     name='RegressionFilter',
        # ),
        # migrations.DeleteModel(
        #     name='TestSet',
        # ),
    ]
