# Generated by Django 4.0.3 on 2022-08-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0003_remove_testset_branch_alter_testinstance_test_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testset',
            name='branch',
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='test_set',
            field=models.ForeignKey(help_text='Test set', on_delete=django.db.models.deletion.CASCADE, to='tra.testsetfilter'),
        ),
        migrations.DeleteModel(
            name='RegressionFilter',
        ),
        migrations.DeleteModel(
            name='TestSet',
        ),
    ]
