# Generated by Django 4.0.3 on 2022-08-30 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tra', '0004_remove_testset_branch_alter_testinstance_test_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPassingLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('utecloud_run_id', models.BigIntegerField(unique=True)),
                ('location', models.CharField(blank=True, help_text='Last passing AirPhone build in TRA Storage', max_length=200, null=True)),
                ('url', models.TextField(blank=True, help_text='Last passing logs url to TRA http storage', null=True)),
                ('size', models.IntegerField(blank=True, help_text='Size of logs directory', null=True)),
                ('build', models.CharField(blank=True, help_text='Last passing build in TRA Storage', max_length=200, null=True)),
                ('airphone', models.CharField(blank=True, help_text='Last passing AirPhone build in TRA Storage', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='test_set',
            field=models.ForeignKey(help_text='Test set', on_delete=django.db.models.deletion.CASCADE, related_name='test_instances', to='tra.testsetfilter'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='test_instance',
            field=models.ForeignKey(help_text='Test instance', on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='tra.testinstance'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Message contents')),
                ('read', models.BooleanField(blank=True, default=False, help_text='Indication if the message was read by the user')),
                ('date', models.DateTimeField(help_text='Date of message')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='testinstance',
            name='last_passing_logs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_instances', to='tra.lastpassinglogs'),
        ),
    ]
