# Generated by Django 4.0.3 on 2022-09-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0005_lastpassinglogs_alter_testinstance_test_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpassinglogs',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='Size of logs directory', null=True),
        ),
    ]
