# Generated by Django 4.0.3 on 2022-09-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0007_lastpassinglogs_downloaded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastpassinglogs',
            options={'verbose_name_plural': 'Last passing logs'},
        ),
    ]
