# Generated by Django 4.0.3 on 2022-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0008_alter_lastpassinglogs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='rp_id',
            field=models.BigIntegerField(blank=True, help_text='ReportingPortal TestInstance Id', null=True),
        ),
    ]
