# Generated by Django 4.0.3 on 2022-09-21 09:52

from django.db import migrations, models
import django.db.models.deletion


def fill_all_testinstances(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    TestRun = apps.get_model("tra", "TestRun")
    Organization = apps.get_model("tra", "Organization")
    TestInstance = apps.get_model("tra", "TestInstance")
    db_alias = schema_editor.connection.alias

    for testinstance in TestInstance.objects.using(db_alias).all():
        tr = testinstance.test_runs.all().first()
        if tr: 
            org = tr.organization
        else:
            org = Organization.objects.using(db_alias).get(name="RAN_L2_SW_KRK_2_SG02")
        testinstance.organization = org
        testinstance.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0009_testinstance_rp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='no_run_in_rp',
            field=models.BooleanField(blank=True, default=False, help_text='No run status in ReportingPortal for the current Feature Build', null=True),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_instances', to='tra.organization'),
        ),
        migrations.RunPython(fill_all_testinstances),
    ]
