# Generated by Django 4.0.3 on 2022-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0010_testinstance_no_run_in_rp_testinstance_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='rp_id',
            field=models.BigIntegerField(blank=True, help_text='ReportingPortal TestInstance Id', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='rp_id',
            field=models.BigIntegerField(help_text='Reporting Portal TestRun id', null=True, unique=True),
        ),
    ]
