# Generated by Django 4.0.3 on 2022-10-21 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0014_auto_20221021_1315'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testsetfilter',
            name='test_set_uniq_constr',
        ),
        migrations.RemoveField(
            model_name='testsetfilter',
            name='testline_type',
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='testline_type',
            field=models.ForeignKey(help_text='Testline type', null=True, on_delete=django.db.models.deletion.CASCADE, to='tra.testlinetype'),
        ),
        migrations.AlterField(
            model_name='testsetfilter',
            name='testline_types',
            field=models.ManyToManyField(help_text='Testline types used for tests in this TestSet', related_name='test_set_filters', to='tra.testlinetype'),
        ),
        migrations.AddConstraint(
            model_name='testsetfilter',
            constraint=models.UniqueConstraint(fields=('test_set_name', 'test_lab_path'), name='test_set_uniq_constr'),
        ),
    ]
