# Generated by Django 4.0.3 on 2022-11-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0015_remove_testsetfilter_test_set_uniq_constr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failmessagetype',
            name='regex',
            field=models.TextField(help_text='Failure message regex', max_length=500),
        ),
    ]
