# Generated by Django 4.0.3 on 2023-03-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0019_remove_lastpassinglogs_utecloud_run_id_char_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testinstance',
            options={'ordering': ['test_set', 'test_case_name']},
        ),
    ]
