# Generated by Django 4.0.3 on 2023-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0022_testrun_execution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrun',
            name='pronto',
            field=models.TextField(blank=True, help_text='Pronto', max_length=100, null=True),
        ),
    ]
