# Generated by Django 4.0.3 on 2023-11-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tra', '0023_testrun_pronto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envissuetype',
            options={'ordering': ['name']},
        ),
    ]
