# Generated by Django 4.0.3 on 2022-05-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testline_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name_plural': 'Laboratories'},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name_plural': 'Switches'},
        ),
        migrations.AlterModelOptions(
            name='topology',
            options={'verbose_name_plural': 'Topologies'},
        ),
        migrations.AlterField(
            model_name='switchport',
            name='connected_to',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_port', to='testline_manager.port'),
        ),
        migrations.AlterField(
            model_name='unitport',
            name='connected_to',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_port', to='testline_manager.port'),
        ),
    ]
