# Generated by Django 4.0.3 on 2022-05-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testline_manager', '0002_alter_laboratory_options_alter_switch_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchport',
            name='connected_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_port', to='testline_manager.port'),
        ),
        migrations.AlterField(
            model_name='unitport',
            name='connected_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_port', to='testline_manager.port'),
        ),
    ]
