# Generated by Django 4.0.3 on 2022-05-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testline_manager', '0003_alter_switchport_connected_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='testline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='testline_manager.testline'),
        ),
    ]
