# Generated by Django 4.0.3 on 2022-06-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testline_manager', '0004_alter_unit_testline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='onelabreservation',
            name='one_lab_status',
        ),
        migrations.AddField(
            model_name='onelabreservation',
            name='localization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='onelabreservation',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='kvm',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='one_lab_reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit', to='testline_manager.onelabreservation'),
        ),
        migrations.CreateModel(
            name='LabKeeper',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='labkeepers', to='testline_manager.team')),
            ],
        ),
        migrations.AddField(
            model_name='onelabreservation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onelab_reservations', to='testline_manager.labkeeper'),
        ),
        migrations.AddField(
            model_name='testline',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testlines', to='testline_manager.team'),
        ),
    ]
