# Generated by Django 4.0.3 on 2022-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_init_stats_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='value',
            field=models.TextField(blank=True, help_text='Value', max_length=4000),
        ),
    ]
